#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : folks
Version  : 0.15.5
Release  : 23
URL      : https://download.gnome.org/sources/folks/0.15/folks-0.15.5.tar.xz
Source0  : https://download.gnome.org/sources/folks/0.15/folks-0.15.5.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : evolution-data-server-data
BuildRequires : evolution-data-server-dev
BuildRequires : libgee-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(gee-0.8)
BuildRequires : readline-dev
BuildRequires : vala
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Folks
=====
libfolks is a library that aggregates people from multiple sources (eg,
Telepathy connection managers) to create metacontacts.

%prep
%setup -q -n folks-0.15.5
cd %{_builddir}/folks-0.15.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664143889
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dtelepathy_backend=false -Dbluez_backend=false  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/folks
cp %{_builddir}/folks-%{version}/COPYING %{buildroot}/usr/share/package-licenses/folks/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
