#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : folks
Version  : 0.12.1
Release  : 4
URL      : https://download.gnome.org/sources/folks/0.12/folks-0.12.1.tar.xz
Source0  : https://download.gnome.org/sources/folks/0.12/folks-0.12.1.tar.xz
Summary  : Library to aggregates people into metacontacts
Group    : Development/Tools
License  : LGPL-2.1
Requires: folks-bin = %{version}-%{release}
Requires: folks-data = %{version}-%{release}
Requires: folks-lib = %{version}-%{release}
Requires: folks-license = %{version}-%{release}
Requires: folks-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : evolution-data-server-data
BuildRequires : libgee-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gee-0.8)
BuildRequires : pkgconfig(libebook-1.2)
BuildRequires : pkgconfig(telepathy-glib)
BuildRequires : readline-dev

%description
Folks
=====
libfolks is a library that aggregates people from multiple sources (eg,
Telepathy connection managers) to create metacontacts.

%package bin
Summary: bin components for the folks package.
Group: Binaries
Requires: folks-data = %{version}-%{release}
Requires: folks-license = %{version}-%{release}

%description bin
bin components for the folks package.


%package data
Summary: data components for the folks package.
Group: Data

%description data
data components for the folks package.


%package dev
Summary: dev components for the folks package.
Group: Development
Requires: folks-lib = %{version}-%{release}
Requires: folks-bin = %{version}-%{release}
Requires: folks-data = %{version}-%{release}
Provides: folks-devel = %{version}-%{release}
Requires: folks = %{version}-%{release}

%description dev
dev components for the folks package.


%package lib
Summary: lib components for the folks package.
Group: Libraries
Requires: folks-data = %{version}-%{release}
Requires: folks-license = %{version}-%{release}

%description lib
lib components for the folks package.


%package license
Summary: license components for the folks package.
Group: Default

%description license
license components for the folks package.


%package locales
Summary: locales components for the folks package.
Group: Default

%description locales
locales components for the folks package.


%prep
%setup -q -n folks-0.12.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556997422
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain -Dtelepathy_backend=false  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/folks
cp COPYING %{buildroot}/usr/share/package-licenses/folks/COPYING
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang folks

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/folks-import
/usr/bin/folks-inspect

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Folks-0.6.typelib
/usr/lib64/girepository-1.0/FolksDummy-0.6.typelib
/usr/lib64/girepository-1.0/FolksEds-0.6.typelib
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.freedesktop.folks.gschema.xml
/usr/share/vala/vapi/folks-dummy.deps
/usr/share/vala/vapi/folks-dummy.vapi
/usr/share/vala/vapi/folks-eds.deps
/usr/share/vala/vapi/folks-eds.vapi
/usr/share/vala/vapi/folks.deps
/usr/share/vala/vapi/folks.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/folks/folks-dummy.h
/usr/include/folks/folks-eds.h
/usr/include/folks/folks.h
/usr/lib64/libfolks-dummy.so
/usr/lib64/libfolks-eds.so
/usr/lib64/libfolks.so
/usr/lib64/pkgconfig/folks-dummy.pc
/usr/lib64/pkgconfig/folks-eds.pc
/usr/lib64/pkgconfig/folks.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/folks/44/backends/bluez/bluez.so
/usr/lib64/folks/44/backends/dummy/dummy.so
/usr/lib64/folks/44/backends/eds/eds.so
/usr/lib64/folks/44/backends/key-file/key-file.so
/usr/lib64/folks/44/backends/ofono/ofono.so
/usr/lib64/libfolks-dummy.so.25
/usr/lib64/libfolks-dummy.so.25.19.1
/usr/lib64/libfolks-eds.so.25
/usr/lib64/libfolks-eds.so.25.19.1
/usr/lib64/libfolks.so.25
/usr/lib64/libfolks.so.25.19.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/folks/COPYING

%files locales -f folks.lang
%defattr(-,root,root,-)

